services:
  mysql:
    image: mysql:8.0.30
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
    command: --max_allowed_packet=20M --default-time-zone=Europe/Berlin

  gpas:
    image: mosaicgreifswald/gpas:2025.1.3
    depends_on:
      - mysql
    ports:
      - "8081:8080"

  epix:
    image: mosaicgreifswald/epix:2025.1.2
    depends_on:
      - mysql
    ports:
      - "8080:8080"
